#:kivy 2.1

BoxLayoutExample:
<BoxLayoutExample>
    orientation: "vertical"
    Button:
        text: "A"
    Button:
        text: "B"
        size_hint: .8, .5
    Button:
        text: "C"

<MainWidget>
    Button:
        text: "Hello"
        size: "100dp", "80dp"
        pos: 100, 200
        color: .5, .6, 1, 1
    
    Label:
        text: "Hello2"
        size: "100dp", "80dp"
        pos: "150dp", "100dp"
        color: .5, .6, 0, 1